version: '3.8'
services:
  backend:
    build:
      context: ./BackEnd_KFC
      dockerfile: Dockerfile
    container_name: kfc_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
    volumes:
      - ./BackEnd_KFC:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: kfc_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
