server {
  listen 80;
  server_name localhost;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /kfcApi/ {
    proxy_pass ${BACKEND_URL}/kfcApi/;
  }

  location /userApi/ {
    proxy_pass ${BACKEND_URL}/userApi/;
  }

  location /cartApi/ {
    proxy_pass ${BACKEND_URL}/cartApi/;
  }

  location /addressApi/ {
    proxy_pass ${BACKEND_URL}/addressApi/;
  }

  location /paymentApi/ {
    proxy_pass ${BACKEND_URL}/paymentApi/;
  }
}
