server {
  listen 80;
  server_name localhost;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /kfcApi/ {
    proxy_pass http://backend:5000/kfcApi/;
  }

  location /userApi/ {
    proxy_pass http://backend:5000/userApi/;
  }

  location /cartApi/ {
    proxy_pass http://backend:5000/cartApi/;
  }

  location /addressApi/ {
    proxy_pass http://backend:5000/addressApi/;
  }

  location /paymentApi/ {
    proxy_pass http://backend:5000/paymentApi/;
  }
}
